# Generated by Django 4.2.3 on 2023-07-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_watchlist_watchitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
