# Generated by Django 4.2.3 on 2023-07-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_instructorprofile_profile_pics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
