# Generated by Django 4.2.3 on 2023-07-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_instructor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Account Name'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
    ]
