# Generated by Django 4.2.3 on 2023-07-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_course_instructor_alter_instructorprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created_at', 'updated_at']},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['created_on', 'updated_on'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['created_on', 'updated_on']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='user.instructor'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.instructor'),
        ),
    ]
